qcacld-3.0: Make hdd_is_pkt_capture_mon_enable() return integer
hdd_is_pkt_capture_mon_enable() has an int return type. Yet it was returning
no value on !WLAN_FEATURE_PKT_CAPTURE.

This fixes the following compilation error:
In file included from ../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:27:
In file included from ../drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:44:
../drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:4304:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
 4304 | }
      | ^

Fixes: 4aa331d05653 ("qcacld-3.0: Don't delete monitor interface when STA interface is down")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>